let lang="bn",currentUser=null,data={activities:[],donors:[],collections:[],expenses:[],custody:[]};
const T={
bn:{title:"মুরাদবাড়ি সামাজিক কল্যাণ ফান্ড",subtitle:"সামাজিক কল্যাণ ও আর্থিক সহায়তা ব্যবস্থাপনা",login:"লগইন",dashboard:"ড্যাশবোর্ড",activities:"কার্যক্রম",collections:"দাতা ও সংগ্রহ",expenses:"খরচ ও সহায়তা",custody:"ফান্ড কোথায়",reports:"রিপোর্ট",security:"নিরাপত্তা",totalCollection:"মোট সংগ্রহ",totalExpense:"মোট খরচ",currentFund:"বর্তমান ফান্ড",donors:"দাতা",yearSummary:"বছরভিত্তিক কার্যক্রম",add:"+ যোগ করুন"},
en:{title:"Murad Bari Social Welfare Fund",subtitle:"Social Welfare & Fund Management System",login:"Login",dashboard:"Dashboard",activities:"Activities",collections:"Donors & Collection",expenses:"Expenses & Assistance",custody:"Fund Custody",reports:"Reports",security:"Security",totalCollection:"Total Collection",totalExpense:"Total Expense",currentFund:"Current Fund",donors:"Donors",yearSummary:"Year-wise Activities",add:"+ Add"}
};
function toggleLang(){lang=lang==="bn"?"en":"bn";document.querySelectorAll("[data-t]").forEach(e=>e.textContent=T[lang][e.dataset.t]||e.textContent);document.getElementById("brand").textContent=T[lang].title;}
function doLogin(){let id=document.getElementById("loginId").value.trim(),p=document.getElementById("loginPass").value;google.script.run.withSuccessHandler(r=>{if(r.success){currentUser=r.user;document.getElementById("loginPage").hidden=true;document.getElementById("app").hidden=false;document.getElementById("user").textContent=r.user.name;load()}else document.getElementById("msg").textContent=r.message}).login(id,p)}
function load(){google.script.run.withSuccessHandler(r=>{data=r;render()}).getData()}
function money(n){return "৳"+Number(n||0).toLocaleString()}
function render(){let c=data.collections.reduce((s,x)=>s+Number(x.amount||0),0),e=data.expenses.reduce((s,x)=>s+Number(x.amount||0),0);document.getElementById("totalCollection").textContent=money(c);document.getElementById("totalExpense").textContent=money(e);document.getElementById("balance").textContent=money(c-e);document.getElementById("donorCount").textContent=data.donors.length;table("activitiesTable",data.activities,["year","name","purpose","status"]);table("collectionsTable",data.collections,["date","donorId","amount","method","note"]);table("expensesTable",data.expenses,["date","recipient","category","amount","method","voucherNo"]);table("custodyTable",data.custody,["locationType","custodianName","amount","date","reason","terms","witnesses","status"])}
function table(id,rows,cols){if(!rows.length){document.getElementById(id).innerHTML="<p>No data yet.</p>";return}let h="<table><thead><tr>"+cols.map(c=>"<th>"+c+"</th>").join("")+"</tr></thead><tbody>";rows.forEach(r=>h+="<tr>"+cols.map(c=>"<td>"+(r[c]??"")+"</td>").join("")+"</tr>");document.getElementById(id).innerHTML=h+"</tbody></table>"}
function show(id){document.querySelectorAll("main>section").forEach(s=>s.hidden=true);document.getElementById(id).hidden=false}
function addDemo(sheet){alert("Database/API প্রস্তুত আছে। "+sheet+"-এর পূর্ণ input form পরবর্তী refinement-এ যুক্ত করা যাবে।")}
function protectedAction(action){let id=prompt("Admin ID");if(id===null)return;let p=prompt("Admin Password");if(p===null)return;if(!confirm("Confirm "+action+"?"))return;google.script.run.withSuccessHandler(r=>alert(r.message)).adminAction(id,p,action)}
